services:
  protonmail-bridge:
    image: dancwilliams/protonmail-bridge:latest@sha256:cab02d1dd299c2993792abdbd5ef78058a7aa8cb553f67438ecf332c8195f6d1
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    volumes:
      - protonmail:/root

volumes:
  protonmail:
    name: protonmail
