services:
  protonmail-bridge:
    image: dancwilliams/protonmail-bridge:latest@sha256:e822dcaeb7b2ade04784e6c2b5ef82a833291590774637538a232958b268c066
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    volumes:
      - protonmail:/root

volumes:
  protonmail:
    name: protonmail
